export const spaceTree = [{
  'holidayCode': '',
  'id': 1,
  'location': '',
  'name': '工位研发',
  'nameEn': '',
  'parentId': 0,
  'parentName': '',
  'path': '-1-',
  'pathName': '工位研发',
  'sort': 0,
  'structure': 0,
  'timeZone': '',
  'delFlag': '0',
  'spaceId': null,
  'tenantId': null,
  'mapId': null,
  'defaultShow': false,
  'children': [{
    'holidayCode': '',
    'id': 3,
    'location': '',
    'name': '零壹广场',
    'nameEn': '',
    'parentId': 1,
    'parentName': '工位研发',
    'path': '-1-3-',
    'pathName': '工位研发,零壹广场',
    'sort': 0,
    'structure': 1,
    'timeZone': '',
    'delFlag': '0',
    'spaceId': null,
    'tenantId': null,
    'mapId': null,
    'defaultShow': false,
    'children': [{
      'holidayCode': '',
      'id': 5,
      'location': '',
      'name': 'A座',
      'nameEn': '',
      'parentId': 3,
      'parentName': '零壹广场',
      'path': '-1-3-5-',
      'pathName': '工位研发,零壹广场,A座',
      'sort': 0,
      'structure': 1,
      'timeZone': '',
      'delFlag': '0',
      'spaceId': null,
      'tenantId': null,
      'mapId': null,
      'defaultShow': false,
      'children': [{
        'holidayCode': '',
        'id': 7,
        'location': '',
        'name': '301',
        'nameEn': '',
        'parentId': 5,
        'parentName': 'A座',
        'path': '-1-3-5-7-',
        'pathName': '工位研发,零壹广场,A座,301',
        'sort': 0,
        'structure': 2,
        'timeZone': '',
        'delFlag': '0',
        'spaceId': null,
        'tenantId': null,
        'mapId': 1,
        'defaultShow': true,
        'children': [],
        'isAuthFlag': true
      }, {
        'holidayCode': '',
        'id': 8,
        'location': '',
        'name': '302',
        'nameEn': '',
        'parentId': 5,
        'parentName': 'A座',
        'path': '-1-3-5-8-',
        'pathName': '工位研发,零壹广场,A座,302',
        'sort': 0,
        'structure': 2,
        'timeZone': '',
        'delFlag': '0',
        'spaceId': null,
        'tenantId': null,
        'mapId': 2,
        'defaultShow': false,
        'children': [],
        'isAuthFlag': true
      }],
      'isAuthFlag': true
    }, {
      'holidayCode': '',
      'id': 6,
      'location': '',
      'name': 'B座',
      'nameEn': '',
      'parentId': 3,
      'parentName': '零壹广场',
      'path': '-1-3-6-',
      'pathName': '工位研发,零壹广场,B座',
      'sort': 0,
      'structure': 1,
      'timeZone': '',
      'delFlag': '0',
      'spaceId': null,
      'tenantId': null,
      'mapId': null,
      'defaultShow': false,
      'children': [{
        'holidayCode': '',
        'id': 9,
        'location': '',
        'name': '301',
        'nameEn': '',
        'parentId': 6,
        'parentName': 'B座',
        'path': '-1-3-6-9-',
        'pathName': '工位研发,零壹广场,B座,301',
        'sort': 0,
        'structure': 2,
        'timeZone': '',
        'delFlag': '0',
        'spaceId': null,
        'tenantId': null,
        'mapId': 3,
        'defaultShow': false,
        'children': [],
        'isAuthFlag': true
      }],
      'isAuthFlag': true
    }],
    'isAuthFlag': true
  }, {
    'holidayCode': '',
    'id': 4,
    'location': '',
    'name': 'A座',
    'nameEn': '',
    'parentId': 1,
    'parentName': '工位研发',
    'path': '-1-4-',
    'pathName': '工位研发,A座',
    'sort': 0,
    'structure': 1,
    'timeZone': '',
    'delFlag': '0',
    'spaceId': null,
    'tenantId': null,
    'mapId': null,
    'defaultShow': false,
    'children': [],
    'isAuthFlag': false
  }],
  'isAuthFlag': true
}]

export const spaceTree2 = [{
  "id": 7,
  "name": "区域",
  "parentId": 0,
  "children": [{"id": 8, "name": "会议室区域", "parentId": 7, "children": []}]
}]

export const space3 = [
  {"id": 2, "name": "会议室区域", "parentId": 1, "children": [
      {id:1,name:'A'},
      {id:2,name:'A1'},
      {id:3,name:'A2'},
      {id:4,name:'A3'},
      {id:5,name:'A4'},
      {id:6,name:'A5'},
    ]}, {
    "id": 3,
    "name": "零一广场",
    "parentId": 1,
    "children": [
      {id:1,name:'A'},
      {id:2,name:'A1'},
      {id:3,name:'A2'},
      {id:4,name:'A3'},
      {id:5,name:'A4'},
      {id:6,name:'A5'},
    ]
  }, {"id": 4, "name": "弄撒", "parentId": 1, "children": [
      {id:1,name:'A'},
      {id:2,name:'A1'},
      {id:3,name:'A2'},
      {id:4,name:'A3'},
      {id:5,name:'A4'},
      {id:6,name:'A5'},
    ]}, {
    "id": 5,
    "name": "雁塔区",
    "parentId": 1,
    "children": [
      {id:1,name:'A'},
      {id:2,name:'A1'},
      {id:3,name:'A2'},
      {id:4,name:'A3'},
      {id:5,name:'A4'},
      {id:6,name:'A5'},
    ]
  }, {"id": 6, "name": "莲湖区", "parentId": 1, "children": [
      {id:1,name:'A'},
      {id:2,name:'A1'},
      {id:3,name:'A2'},
      {id:4,name:'A3'},
      {id:5,name:'A4'},
      {id:6,name:'A5'},
    ]}
]


export const initData = [
  {id: 3, parentId: 1},
  {id: 4, parentId: 3}
]

export const init2 = [{
  "children": [{
    "children": [],
    "delFlag": "0",
    "holidayCode": "1",
    "id": 2,
    "location": "",
    "name": "会议室区域",
    "nameEn": "",
    "parentId": 1,
    "parentName": "meetingdev",
    "path": "-1-2-",
    "pathName": "meetingdev,会议室区域",
    "sort": 2,
    "structure": 2,
    "timeZone": "Asia/Shanghai"
  }, {
    "children": [],
    "delFlag": "0",
    "holidayCode": "1",
    "id": 3,
    "location": "",
    "name": "零一广场",
    "nameEn": "",
    "parentId": 1,
    "parentName": "meetingdev",
    "path": "-1-3-",
    "pathName": "meetingdev,零一广场",
    "sort": 3,
    "structure": 2,
    "timeZone": "Asia/Shanghai"
  }, {
    "children": [],
    "delFlag": "0",
    "holidayCode": "1",
    "id": 4,
    "location": "",
    "name": "弄撒",
    "nameEn": "",
    "parentId": 1,
    "parentName": "meetingdev",
    "path": "-1-4-",
    "pathName": "meetingdev,弄撒",
    "sort": 4,
    "structure": 2,
    "timeZone": ""
  }, {
    "children": [],
    "delFlag": "0",
    "holidayCode": "1",
    "id": 5,
    "location": "",
    "name": "雁塔区",
    "nameEn": "",
    "parentId": 1,
    "parentName": "meetingdev",
    "path": "-1-5-",
    "pathName": "meetingdev,雁塔区",
    "sort": 5,
    "structure": 2,
    "timeZone": ""
  }, {
    "children": [],
    "delFlag": "0",
    "holidayCode": "1",
    "id": 6,
    "location": "",
    "name": "莲湖区",
    "nameEn": "",
    "parentId": 1,
    "parentName": "meetingdev",
    "path": "-1-6-",
    "pathName": "meetingdev,莲湖区",
    "sort": 6,
    "structure": 2,
    "timeZone": ""
  }],
  "delFlag": "0",
  "holidayCode": "1",
  "id": 1,
  "location": "",
  "name": "meetingdev",
  "nameEn": "",
  "parentId": 0,
  "parentName": "",
  "path": "-1-",
  "pathName": "meetingdev",
  "sort": 0,
  "structure": 1,
  "timeZone": ""
}, {
  "children": [],
  "delFlag": "0",
  "holidayCode": "1",
  "id": 2,
  "location": "",
  "name": "会议室区域",
  "nameEn": "",
  "parentId": 1,
  "parentName": "meetingdev",
  "path": "-1-2-",
  "pathName": "meetingdev,会议室区域",
  "sort": 2,
  "structure": 2,
  "timeZone": "Asia/Shanghai"
}]
